[versions]
appcompat = "1.7.1"
coreKtx = "1.17.0"
navigation = "2.9.5"
mediarouter = "1.8.1"
palette = "1.0.0"
preference = "1.2.1"
splashscreen = "1.0.1"

lifecycle = "2.9.4"

#Google
gson = "2.13.2"
material = "1.12.0"

#Google Play
featureDelivery = "2.1.0"
googlePlayReview = "2.0.2"

androidSnowfall = "1.2.1"
fadingedgelayout = "1.0.0"
fastscroll = "1.3.0"

glide = "4.16.0"

afollestadCab = "2.0.1"
afollestadDialog = "3.3.0"

koin = "4.1.1"

advrecyclerview = "1.0.0"
androidIabLibrary = "2.2.0"
customactivityoncrash = "2.4.0"
heinrichreimersoftware = "2.0.0"
insetter = "0.6.1"
keyboardvisibilityevent = "3.0.0-RC3"
licensesdialog = "2.2.0"
retrofit = "1.9.0"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

agp = "8.12.3"
kotlin = "2.2.20"

#Plugins
devToolsKsp = "2.2.20-2.0.3"

[libraries]
#Android
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation" }
androidx-mediarouter = { group = "androidx.mediarouter", name = "mediarouter", version.ref = "mediarouter" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }

androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }

#lifecycle
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

#Google
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-code-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

#Google Play
google-android-play-featureDelivery = { module = "com.google.android.play:feature-delivery", version.ref = "featureDelivery" }
google-android-play-review = { module = "com.google.android.play:review", version.ref = "googlePlayReview" }

#GitHub
github-bosphere-fadingedgelayout = { module = "com.github.bosphere.android-fadingedgelayout:fadingedgelayout", version.ref = "fadingedgelayout" }
github-jetradarmobile-androidSnowfall = { module = "com.github.jetradarmobile:android-snowfall", version.ref = "androidSnowfall" }
github-zhanghai-fastscroll = { module = "me.zhanghai.android.fastscroll:library", version.ref = "fastscroll" }

#glide
github-bumptech-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
github-bumptech-glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
github-bumptech-glide-okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }

#material dialog
afollestad-material-cab = { module = "com.afollestad:material-cab", version.ref = "afollestadCab" }
afollestad-material-dialogs-color = { module = "com.afollestad.material-dialogs:color", version.ref = "afollestadDialog" }
afollestad-material-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "afollestadDialog" }
afollestad-material-dialogs-input = { module = "com.afollestad.material-dialogs:input", version.ref = "afollestadDialog" }

#Koin
insert-koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
insert-koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

#Other
anjlab-android-iab-v3-library = { module = "com.anjlab.android.iab.v3:library", version.ref = "androidIabLibrary" }
cat-ereza-customactivityoncrash = { module = "cat.ereza:customactivityoncrash", version.ref = "customactivityoncrash" }
chrisbanes-insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
heinrichreimersoftware-materialIntro = { module = "com.heinrichreimersoftware:material-intro", version.ref = "heinrichreimersoftware" }
h6ah4i-advrecyclerview = { module = "com.h6ah4i.android.widget.advrecyclerview:advrecyclerview", version.ref = "advrecyclerview" }
psdev-licensesDialog = { module = "de.psdev.licensesdialog:licensesdialog", version.ref = "licensesdialog" }
squareup-retrofit = { module = "com.squareup.retrofit:retrofit", version.ref = "retrofit" }
yslibrary-kayboardvisiblityevent = { module = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent", version.ref = "keyboardvisibilityevent" }

#Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devToolsKsp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }